myaxf/axf/urls.py
from django.conf.urls import url
from axf import views

urlpatterns = [
    url(r'^home/',views.home,name='home'),
    url(r'^mine/',views.mine,name='mine'),
    url(r'^market$',views.market,name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/',views.user_market,name='user_market'),
    url(r'^addCart/',views.add_cart,name='addCart'),
    url(r'^subCart/',views.sub_cart,name='subCart'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^changeselect/',views.changeselect,name='changeselect'),
    url(r'^orderinfo/',views.orderinfo,name='orderinfo'),
    url(r'^changeOrderStatus/',views.changeOrderStatus,name='changeOrderStatus'),


]

myaxf/myaxf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.contrib.staticfiles.urls import static
from myaxf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('axf.urls',namespace='axf')),
    url(r'^user/',include('user.urls',namespace='user')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myaxf/axf/models.py
from django.db import models

# Create your models here.
from user.models import UserModel


class Main(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=16)

    class Meta:
        abstract = True

class MainWheel(Main):
    class Meta:
        db_table = 'axf_wheel'

class MainNav(Main):
    class Meta:
        db_table = 'axf_nav'

class MainMustBuy(Main):

    class Meta:
        db_table = 'axf_mustbuy'

class MainShop(Main):

    class Meta:
        db_table = 'axf_shop'

class MainShow(Main):
    categoryid = models.CharField(max_length=16)
    brandname = models.CharField(max_length=100)

    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=16)
    productid1 = models.CharField(max_length=16)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField(default=0)
    marketprice1 = models.FloatField(default=1)

    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField(default=0)
    marketprice2 = models.FloatField(default=1)

    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField(default=0)
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = 'axf_mainshow'

class FoodType(models.Model):
    typeid = models.CharField(max_length=16)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_foodtypes'

class Goods(models.Model):
    productid = models.CharField(max_length=16)
    productimg = models.CharField(max_length=200)
    productname = models.CharField(max_length=100)
    productlongname = models.CharField(max_length=200) # 商品的规格
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    marketprice = models.FloatField(default=1) # 原价
    categoryid = models.CharField(max_length=16)
    childcid = models.CharField(max_length=16)
    childcidname = models.CharField(max_length=100)
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)
    productnum = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_goods'


class CartModel(models.Model):
    user = models.ForeignKey(UserModel) #关联用户
    goods = models.ForeignKey(Goods) # 关联商品
    c_num = models.IntegerField(default=1) #商品的个数
    is_select = models.BooleanField(default=True) # 是否选择

    class Meta:
        db_table = 'axf_cart'

class OrderModel(models.Model):
    user = models.ForeignKey(UserModel) # 关联用户
    o_num = models.CharField(max_length=64)
    # 0代表已下单，但是未付款 ， 1已付款未发货 2已付款已发货
    o_status = models.IntegerField(default=0) # 状态
    o_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'axf_order'

class OrderGoodsModel(models.Model):
    goods = models.ForeignKey(Goods) #关联的商品
    order = models.ForeignKey(OrderModel) #关联的订单
    goods_num = models.IntegerField(default=1) #商品的个数

    class Meta:
        db_table = 'axf_order_goods'

myaxf/templates/market/market.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/market.css' %}">
{% endblock %}

{% block EXTJS %}

     <script type="text/javascript" src="{% static 'app/market/js/market.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/common/function.js' %}"></script>

{% endblock %}


{% block content %}

    <div id="market">

        <aside>

            <ul>

                <!--闪购分类展示-->
                {% for types in foodtypes %}
                    <li>
                        <!--链接地址，点击获取分类下的商品信息-->
                        <a href="">{{ types.typename }}</a>
                        {% ifequal types.typeid typeid   %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
                <!--处理数据结束-->

            </ul>

        </aside>


        <section>
            <nav>
                <ul>
                    <li id="all_types"><span>全部类型<span id="all_type_logo"
                                                       class="glyphicon glyphicon-chevron-down"></span></span></li>
                    <li id="sort_rule"><span>综合排序<span id="sort_rule_logo" class="glyphicon glyphicon-chevron-down"></span></span></li>
                </ul>
            </nav>

            <menu>
                <ul>
                    {% csrf_token %}
                    <!--商品信息展示-->
                    {% for gds in goods %}
                        <li>
                            <a href="#">
                                <img src="{{ gds.productimg }}" alt="">
                                <div class="shoppingInfo">
                                    <h6></h6>
                                    <p class="detailTag">
                                        <span>精选</span>
                                        <span></span>
                                    </p>
                                    <p class="unit">
                                        {{ gds.productlongname }}
                                    </p>
                                    <p class="price">
                                        <span>¥{{ gds.price }}</span>
                                        <s>¥{{ gds.marketprice }}</s>
                                    </p>
                                </div>
                            </a>
                        <section>
                            <button goodsid="" onclick="subCart({{ gds.id }})">-</button>
{#                            {% if user_cart %}#}
{#                            {% for cart_goods in gds.cartmodel_set.all %}#}
{#                                {% ifequal cart_goods.user_id user.id %}#}
                            <span id="num_{{ gds.id }}">0</span>
{#                                {% endifequal %}#}
{#                                {% endfor %}#}
{#                            {% else %}#}
                            <button goodsid="" onclick="addCart({{ gds.id }})">+</button>
                        </section>
                        </li>
                        {% endfor %}
{#                        {% endif %}#}
                    <!--处理数据结束-->
                </ul>

                <div id="all_types_container">
                    <div>
                        <!--加载全部分类的数据-->
                        {% for child in child_list %}
                            <a href="{% url 'axf:user_market' typeid child.1 '0' %}">
                                <span>{{ child.0 }}</span>
                            </a>
                        {% endfor %}
                        <!--处理数据结束-->


                    </div>
                </div>


                <div id="sort_container">
                    <div>
{#      排序传递的也是状态码   0 , 1 ,2  , 3 ,4 ,5...                    #}
                        <a href="{% url 'axf:user_market' typeid cid '0' %}">
                            <span>综合排序</span>
                        </a>
                        <a href="{% url 'axf:user_market' typeid cid '1' %}">
                            <span>销量排序</span>
                        </a>
                        <a href="{% url 'axf:user_market' typeid cid '2' %}">
                            <span>价格降序</span>
                        </a>
                        <a href="{% url 'axf:user_market' typeid cid '3' %}">
                            <span>价格升序</span>
                        </a>

                    </div>
                </div>

            </menu>

        </section>


    </div>


{% endblock %}